### ISSUE TITLE
[Feature request] Shuffle feature

### ISSUE THREAD

**Issue by Anopob** [djuretic/riichi-mahjong-trainer#1]
Hi there, I would like to make a feature request if it's in scope. I would like a toggle (similar to Numbered tiles) that shuffles the tiles in the hand. So for example right now it might give me 1223466667778, but with shuffle turned on it can be a random order like 6732462177866. This increases the difficulty by a significant margin but can be a very fun exercise to try.

If this is in scope / desired, I would love to try and implement this myself. I have no clue about elm but seems like maybe I can use the elm-community/random-extra package, with its Random.List shuffle function in renderRows or something like that. Feel free to suggest how to do it or even implement it yourself if it's easier for you.

If it's not in scope, that's ok too.

Thanks for making a great open-source app like this, it's been fun to train!

**Comment by djuretic** [comment]
It's nice to know that the app has been useful to you, thanks!

I wouldn't add that option at the moment, I prefer to keep the app's focus aimed at beginner/intermediate level players and don't add too many configuration options. Anyway, you are on the right track, Random.List suffle from elm-community/random-extra package is the function to use.
