### ISSUE TITLE
incorrect wait recognition

### ISSUE THREAD

**Issue by rumok** [djuretic/riichi-mahjong-trainer#2]
![2023-07-08_09-30-05](https://github.com/djuretic/riichi-mahjong-trainer/assets/25028665/37658913-9f1a-4b20-86b0-249622326318)

**Comment by djuretic** [comment]
Hi @rumok, can you explain why the 4 of characters is a valid wait?

**Comment by rumok** [comment]
My fault, I thought that two tiles are my pick. Thanks for quick reply.
