### ISSUE TITLE
Answer is incorrect

### ISSUE THREAD

**Issue by jjpark58** [djuretic/riichi-mahjong-trainer#3]
Correct answer should be 25m. Only shows 5m as answer.
![image](https://github.com/djuretic/riichi-mahjong-trainer/assets/68671561/e2d23132-c4fb-499f-89ef-d8d8d9e6e39a)

**Comment by djuretic** [comment]
Thanks for reporting the error @jjpark58! I'll notify you when this is fixed.

**Comment by djuretic** [comment]
@jjpark58 I've updated the trainer, now it is working as intended:

![bildo](https://github.com/djuretic/riichi-mahjong-trainer/assets/1175986/5fe87fe6-17ee-4083-8d24-ce98cbb2b6d7)
